[profile.default]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = "0.8.28"

# These settings should be used for snapshots
optimizer = true
optimizer_runs = 1000000

bytecode_hash = "none"
cbor_metadata = false

[fuzz]
runs = 2048